language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: PQ3qeEX4ShLQPmDgBcx4/3/Op7PyX8CUzS6iXBMjE7ad4Lat3wYf4LWM6F5FLOAvWTNP9e9tktKMEq+8v+qmILHdLNPqwB//WnwM7fmzIWftCMprr5s1UTbfl2X773Gbs+7r2hZ5m2s1sSRtq0PdB1Ic79WjixltqX8y9C6e+CTh7kidK3FQAkTIf/1/YLa5MFoN8k2nqxJUecCazIXOhHxD8/N/MQAJjqGizqC7DkL7qOdlTLEaminDgUabZjyHxVNFyFiSFpt3C1rDcMiUl3SFM8/P+amnm5YL7ZMiJJsHA1POKl727HWUksxC9JBQeVgLrEO0qHoi8DKXM8eDUTyFxJauW3q5Ta1wPrU4sN4B6iqxEQF+5g92l3OgIuM0DlHF9v3dCHnfb3q7wrU5JodPfxIA+E/mUh77B2VSe0cyuQdVAhaquLxRKpOcMmQwMe4rQOh4LoTUHiOEUJZGkCP/e7bsXCV36YmGXze+epo3Q0z7C05OpmBoGM5ehnr8SB2u9xdP9hWJz8x0ljNIDxXHb7U5E6blTJI1vuhzLa9pzUh91GM4MlYBOGcXDX+AdZD5JwfTT1g4N916/P2tryBsoHhcnMz3IWIX2MOf/Vf/ZeDxO53zcFOS/Op1m+Y9lpq7YYfcUFLfXbE3Mb3OeHutS7k0h9iF8hmoAsHaFVw=
