language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: aOdaWDI0HLIDt2fMUUWCnVTdcD+s/fa9CcUPui1Bz9IU01Vro1ksTi7t2skWByq8cnkBnK+FNo0eWZjlgyhbGU2amauLA0Z7AUh8MX14mE+6xOfC+OTqgXDBU4d5WuQzmyB9EJdYlZJtNfKmtWQyzj78oy9kaEOk4Pv9VkSeuDvlci1TsZDdcl//TkhjohdbwfJnz4qO5j5yCpsP0f32UbPdP4IsoWHItUlCVh0o+J1Kf6Cgy7v47GfkJ79nqncAvvqmwXPmklyp8aDdyA2cBmgHEmOYMJ5+BFLuRhx4VNhpD3ewKFKQfU+KC1HnaFyudJAymyuzq/VsURTpcz+CuBsWTNRKNOEQoaMkwt3oVAw0vqg7dQxBqpY1pp/ODzfIF7ni3wMJNDVwsYIx6CYgkL+kZMyaMNdHfZYSGAuzqhivyCB+UAHrusx4qd+eJvcnUcvrXIvEKCu+qSMC/S/MZS2geiZ8Nd4LTmLilBgsUDaZLCifbkeRJ7v+KUL8FqQ5zqjfgLhEypchhssKeNX5v/Tw7fvKQKj86Ere46YjZTTNkdEKdn9MClTXkyQJ2KD/ZAQw+DI2Ca1qoV9whqYQw7oRgfNW+c1KO+cFeKGCZ5hGOxtMx5VcA6Fzcq+o75/JPN2xH6DBPX+9b94xPmmDP1GfIne6sLDLV+UEBxPnEag=
  app: vast-hollows-73271
