language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: cUnfFsj5HFLfQoZsfVwalHR40JUs9Mb3E+VsAqbiZOdemxxBEdc8u9yXNuTEdbSyiNdKn6Q/hVV04o/nwynkJMKVevb/yO5mfNV9RevL1ywO1rHEoWRbnrHNDH/oHBlBaURDzb8pmjQ/j35U15hyLkZUgszr6uGJtImo86hn4p7yvIolsn423PNprLivnU7YPzAIeMNpUvsyjEsukAMp1KRFHZF9y8HigUyCrnbvxBPpptiHUqK7LwxTe5Jqd6KkgCmahgaCDOSBjdhv4eNBItlfi8+21TVzzLrCv0Lc2jfoMxDXmlIKpzAEpnQZ77WYnISEs4fHS5C8bYlbawDPZty0/ArbQ1Nw0wsdIP7TKzQ96S+P/v6r9lkMCZFDspNvGLu1hUyusNd+/gPgJlwenpzeUPrKffPAlz3QVGLs6zegCxvORX/uVlSAuDmFINHByQQwPD+oIiu46UJhBMVK5eXVH6E9ENAYi91x6sd1uE9sdfP+GDp2jpp9RbQ2pe/03387clbuB4M7ATv7YD1w+vRxjY8nB3KgXXttMMMkFqTqVtF4pcG32kLbBoB9xNNYqjSA7e/HSXJOX4OULOaiRCjiZFnbupjd9ILpxKO2uEZK5wlyNUeqKOhAhI+jtUIyjJlt8yp6h+i3Tq6z41N0XMnmhKV+NtXfyYJdYzrSRCs=
